### ISSUE TITLE
error & warning duplicates

### ISSUE THREAD

**Issue by fredyvonvinet** [fredyvonvinet/ANTLR4-Plugins-for-NetBeans#36]
Each error & warning appears in duplicate.

**Comment by fredyvonvinet** [comment]
corrected

**Comment by Chris2011** [comment]
I still have the problems with the duplicates.

**Comment by Chris2011** [comment]
For me it happens, when I switch between 2 g4 files.

**Comment by fredyvonvinet** [comment]
The problem has been soled in 1.2.1. So it is normal you encounter that problem because I just forget to publish it.  I don't know what happened on 4 March. I was sure it was published but it is not the case.

I will do it today.

**Comment by Chris2011** [comment]
Ahh ok, no problem. Thx to let me know it :)
